spring:
  application:
    name: product-service

  datasource:
    url: "jdbc:postgresql://127.0.0.1:5433/tols?currentSchema=product_service"
    username: "postgres"
    password: "Prabal98@"
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: "product_service"
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    format-sql: "true"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,liveness,readiness

server:
  port: 8081
